// <auto-generated />
using System;
using AssuncaoDistribution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssuncaoDistribution.Migrations
{
    [DbContext(typeof(AssuncaoDistributionContext))]
    [Migration("20220118000933_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AssuncaoDistribution.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Cep")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CnpjOrCpf")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactCli")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.ItemsOrderSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AmountOrder")
                        .HasColumnType("int");

                    b.Property<double>("PriceOrder")
                        .HasColumnType("double");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.HasIndex("SalesId");

                    b.ToTable("ItemsOrderSales");
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AmountProd")
                        .HasColumnType("int");

                    b.Property<int>("Measures")
                        .HasColumnType("int");

                    b.Property<int>("MeasuresId")
                        .HasColumnType("int");

                    b.Property<string>("NameProd")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("PriceProd")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddresProv")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CepProv")
                        .HasColumnType("int");

                    b.Property<string>("CityProv")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CnpjOrCpfProv")
                        .HasColumnType("bigint");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CorporateName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DistrictProv")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EmailProv")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FantasyName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Fax")
                        .HasColumnType("int");

                    b.Property<int>("PhoneProv")
                        .HasColumnType("int");

                    b.Property<double>("Portage")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("PriceOrder")
                        .HasColumnType("double");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.PurchaseOrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<double>("PriceItems")
                        .HasColumnType("double");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.Property<int>("PurchOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.HasIndex("PurchOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("PriceSale")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.ItemsOrderSale", b =>
                {
                    b.HasOne("AssuncaoDistribution.Models.Products", "Prod")
                        .WithMany()
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssuncaoDistribution.Models.SalesOrder", "Sales")
                        .WithMany()
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.PurchaseOrder", b =>
                {
                    b.HasOne("AssuncaoDistribution.Models.Provider", "Providers")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.PurchaseOrderItems", b =>
                {
                    b.HasOne("AssuncaoDistribution.Models.Products", "Prod")
                        .WithMany()
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssuncaoDistribution.Models.PurchaseOrder", "PurchOrder")
                        .WithMany()
                        .HasForeignKey("PurchOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssuncaoDistribution.Models.SalesOrder", b =>
                {
                    b.HasOne("AssuncaoDistribution.Models.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
